/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type { Guarded, GuardedInterface } from "../../../src/access/Guarded";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "newGuardian",
        type: "address",
      },
    ],
    name: "GuardianAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "removedGuardian",
        type: "address",
      },
    ],
    name: "GuardianRemoved",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "isGuardian",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101b1806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80630c68ba2114610030575b600080fd5b61004a60048036038101906100459190610118565b610060565b6040516100579190610160565b60405180910390f35b60008060008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060009054906101000a900460ff169050919050565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006100e5826100ba565b9050919050565b6100f5816100da565b811461010057600080fd5b50565b600081359050610112816100ec565b92915050565b60006020828403121561012e5761012d6100b5565b5b600061013c84828501610103565b91505092915050565b60008115159050919050565b61015a81610145565b82525050565b60006020820190506101756000830184610151565b9291505056fea2646970667358221220456dc487bbe8ceba60309a3651e6691956786e35a2ba1f6e2ad8cf8a917ee92764736f6c63430008110033";

type GuardedConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GuardedConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Guarded__factory extends ContractFactory {
  constructor(...args: GuardedConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Guarded> {
    return super.deploy(overrides || {}) as Promise<Guarded>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Guarded {
    return super.attach(address) as Guarded;
  }
  override connect(signer: Signer): Guarded__factory {
    return super.connect(signer) as Guarded__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GuardedInterface {
    return new utils.Interface(_abi) as GuardedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Guarded {
    return new Contract(address, _abi, signerOrProvider) as Guarded;
  }
}
