/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  LibClone,
  LibCloneInterface,
} from "../../../../solady/src/utils/LibClone";

const _abi = [
  {
    inputs: [],
    name: "DeploymentFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "ETHTransferFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "SaltDoesNotStartWith",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212201d71a7b0b683be72d076ce690aec871b6587fe3641953963c65a7778a6b7cd9564736f6c63430008170033";

type LibCloneConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LibCloneConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LibClone__factory extends ContractFactory {
  constructor(...args: LibCloneConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<LibClone> {
    return super.deploy(overrides || {}) as Promise<LibClone>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): LibClone {
    return super.attach(address) as LibClone;
  }
  override connect(signer: Signer): LibClone__factory {
    return super.connect(signer) as LibClone__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibCloneInterface {
    return new utils.Interface(_abi) as LibCloneInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LibClone {
    return new Contract(address, _abi, signerOrProvider) as LibClone;
  }
}
