/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  UserOperationLib,
  UserOperationLibInterface,
} from "../../../../account-abstraction/contracts/core/UserOperationLib";

const _abi = [
  {
    inputs: [],
    name: "PAYMASTER_DATA_OFFSET",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PAYMASTER_POSTOP_GAS_OFFSET",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PAYMASTER_VALIDATION_GAS_OFFSET",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346100195760bb908161001f823930815050f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c90816325093e1b14606c57508063b29a8ff41460565763ede3150214603e57600080fd5b80600319360112605357602060405160348152f35b80fd5b5080600319360112605357602060405160148152f35b90508160031936011260815780602460209252f35b5080fdfea2646970667358221220b6adffb7d2997c7cd8a3d77d719d250ebbca3b60f36fd605f8b55fd446609c6b64736f6c63430008170033";

type UserOperationLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UserOperationLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class UserOperationLib__factory extends ContractFactory {
  constructor(...args: UserOperationLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<UserOperationLib> {
    return super.deploy(overrides || {}) as Promise<UserOperationLib>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): UserOperationLib {
    return super.attach(address) as UserOperationLib;
  }
  override connect(signer: Signer): UserOperationLib__factory {
    return super.connect(signer) as UserOperationLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UserOperationLibInterface {
    return new utils.Interface(_abi) as UserOperationLibInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UserOperationLib {
    return new Contract(address, _abi, signerOrProvider) as UserOperationLib;
  }
}
