[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
test = "test/foundry"
cache_path = "forge_cache"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
