/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../common";
import type {
  ExecutionHelper,
  ExecutionHelperInterface,
} from "../../../../../src/modular-etherspot-wallet/erc7579-ref-impl/core/ExecutionHelper";

const _abi = [
  {
    inputs: [],
    name: "ExecutionFailed",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "batchExecutionindex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "result",
        type: "bytes",
      },
    ],
    name: "TryExecuteUnsuccessful",
    type: "event",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220ceab589d1fbe18f65ea53bb26453e9abb9cd6db7d6e42f74d1594c2b34a474cd64736f6c63430008170033";

type ExecutionHelperConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ExecutionHelperConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ExecutionHelper__factory extends ContractFactory {
  constructor(...args: ExecutionHelperConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ExecutionHelper> {
    return super.deploy(overrides || {}) as Promise<ExecutionHelper>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ExecutionHelper {
    return super.attach(address) as ExecutionHelper;
  }
  override connect(signer: Signer): ExecutionHelper__factory {
    return super.connect(signer) as ExecutionHelper__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ExecutionHelperInterface {
    return new utils.Interface(_abi) as ExecutionHelperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ExecutionHelper {
    return new Contract(address, _abi, signerOrProvider) as ExecutionHelper;
  }
}
