/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGuardianPlugin } from "./IGuardianPlugin";
export type { IMultipleOwnerPlugin } from "./IMultipleOwnerPlugin";
export type { ISingleOwnerPlugin } from "./ISingleOwnerPlugin";
