/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FactoryStaker } from "./FactoryStaker";
export type { ModularEtherspotWallet } from "./ModularEtherspotWallet";
export type { ModularEtherspotWalletFactory } from "./ModularEtherspotWalletFactory";
