/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../../common";
import type {
  MockDelegateTarget,
  MockDelegateTargetInterface,
} from "../../../../../../src/modular-etherspot-wallet/erc7579-ref-impl/test/mocks/MockDelegateTarget";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
    ],
    name: "sendValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346100155760ed908161001b8239f35b600080fdfe60806040526004361015601157600080fd5b6000803560e01c6324a084df14602657600080fd5b3460b457604036600319011260b457806004356001600160a01b038116810360b15781808092602435905af1503d1560ae573d67ffffffffffffffff808211609a57601f19603f81601f6040519501160116820191821091111760865780f35b634e487b7160e01b81526041600452602490fd5b634e487b7160e01b83526041600452602483fd5b80f35b50fd5b80fdfea2646970667358221220a8d1437a25cf32089fcea845c8c687475ec2e6313a94d562fdcc20127465198264736f6c63430008170033";

type MockDelegateTargetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockDelegateTargetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockDelegateTarget__factory extends ContractFactory {
  constructor(...args: MockDelegateTargetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<MockDelegateTarget> {
    return super.deploy(overrides || {}) as Promise<MockDelegateTarget>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): MockDelegateTarget {
    return super.attach(address) as MockDelegateTarget;
  }
  override connect(signer: Signer): MockDelegateTarget__factory {
    return super.connect(signer) as MockDelegateTarget__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockDelegateTargetInterface {
    return new utils.Interface(_abi) as MockDelegateTargetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockDelegateTarget {
    return new Contract(address, _abi, signerOrProvider) as MockDelegateTarget;
  }
}
