/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EtherspotWallet__factory } from "./EtherspotWallet__factory";
export { EtherspotWalletFactory__factory } from "./EtherspotWalletFactory__factory";
