/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as etherspotWalletV1 from "./etherspot-wallet-v1";
export * as modularEtherspotWallet from "./modular-etherspot-wallet";
