/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type { LibErrors, LibErrorsInterface } from "../../src/LibErrors";

const _abi = [
  {
    inputs: [],
    name: "ACL_AlreadyGuardian",
    type: "error",
  },
  {
    inputs: [],
    name: "ACL_AlreadyOwner",
    type: "error",
  },
  {
    inputs: [],
    name: "ACL_NoSelfRemoval",
    type: "error",
  },
  {
    inputs: [],
    name: "ACL_NonExistantGuardian",
    type: "error",
  },
  {
    inputs: [],
    name: "ACL_NonExistantOwner",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAddress",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212209649852e2f5a11773a2cde59d751c4161ee951d1c03d8dae9ab76c898585b77e64736f6c63430008110033";

type LibErrorsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LibErrorsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LibErrors__factory extends ContractFactory {
  constructor(...args: LibErrorsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<LibErrors> {
    return super.deploy(overrides || {}) as Promise<LibErrors>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): LibErrors {
    return super.attach(address) as LibErrors;
  }
  override connect(signer: Signer): LibErrors__factory {
    return super.connect(signer) as LibErrors__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibErrorsInterface {
    return new utils.Interface(_abi) as LibErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LibErrors {
    return new Contract(address, _abi, signerOrProvider) as LibErrors;
  }
}
