/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC165__factory } from "./IERC165__factory";
export { IMulticall3__factory } from "./IMulticall3__factory";
