/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface MSCAFactoryFixtureInterface extends utils.Interface {
  functions: {
    "UNSTAKE_DELAY()": FunctionFragment;
    "accountImplementation()": FunctionFragment;
    "addStake()": FunctionFragment;
    "createAccount(address,uint256)": FunctionFragment;
    "entryPoint()": FunctionFragment;
    "getAddress(address,uint256)": FunctionFragment;
    "getSalt(address,uint256)": FunctionFragment;
    "guardianPlugin()": FunctionFragment;
    "guardianPluginManifestHash()": FunctionFragment;
    "multipleOwnerPlugin()": FunctionFragment;
    "multipleOwnerPluginManifestHash()": FunctionFragment;
    "self()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "UNSTAKE_DELAY"
      | "accountImplementation"
      | "addStake"
      | "createAccount"
      | "entryPoint"
      | "getAddress"
      | "getSalt"
      | "guardianPlugin"
      | "guardianPluginManifestHash"
      | "multipleOwnerPlugin"
      | "multipleOwnerPluginManifestHash"
      | "self"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "UNSTAKE_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accountImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "addStake", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createAccount",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "entryPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAddress",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSalt",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "guardianPlugin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "guardianPluginManifestHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "multipleOwnerPlugin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "multipleOwnerPluginManifestHash",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "self", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "UNSTAKE_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accountImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entryPoint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSalt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "guardianPlugin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "guardianPluginManifestHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multipleOwnerPlugin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multipleOwnerPluginManifestHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "self", data: BytesLike): Result;

  events: {};
}

export interface MSCAFactoryFixture extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MSCAFactoryFixtureInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    UNSTAKE_DELAY(overrides?: CallOverrides): Promise<[number]>;

    accountImplementation(overrides?: CallOverrides): Promise<[string]>;

    addStake(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createAccount(
      owner: PromiseOrValue<string>,
      salt: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    entryPoint(overrides?: CallOverrides): Promise<[string]>;

    getAddress(
      owner: PromiseOrValue<string>,
      salt: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getSalt(
      owner: PromiseOrValue<string>,
      salt: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    guardianPlugin(overrides?: CallOverrides): Promise<[string]>;

    guardianPluginManifestHash(overrides?: CallOverrides): Promise<[string]>;

    multipleOwnerPlugin(overrides?: CallOverrides): Promise<[string]>;

    multipleOwnerPluginManifestHash(
      overrides?: CallOverrides
    ): Promise<[string]>;

    self(overrides?: CallOverrides): Promise<[string]>;
  };

  UNSTAKE_DELAY(overrides?: CallOverrides): Promise<number>;

  accountImplementation(overrides?: CallOverrides): Promise<string>;

  addStake(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createAccount(
    owner: PromiseOrValue<string>,
    salt: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  entryPoint(overrides?: CallOverrides): Promise<string>;

  getAddress(
    owner: PromiseOrValue<string>,
    salt: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getSalt(
    owner: PromiseOrValue<string>,
    salt: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  guardianPlugin(overrides?: CallOverrides): Promise<string>;

  guardianPluginManifestHash(overrides?: CallOverrides): Promise<string>;

  multipleOwnerPlugin(overrides?: CallOverrides): Promise<string>;

  multipleOwnerPluginManifestHash(overrides?: CallOverrides): Promise<string>;

  self(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    UNSTAKE_DELAY(overrides?: CallOverrides): Promise<number>;

    accountImplementation(overrides?: CallOverrides): Promise<string>;

    addStake(overrides?: CallOverrides): Promise<void>;

    createAccount(
      owner: PromiseOrValue<string>,
      salt: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    entryPoint(overrides?: CallOverrides): Promise<string>;

    getAddress(
      owner: PromiseOrValue<string>,
      salt: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getSalt(
      owner: PromiseOrValue<string>,
      salt: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    guardianPlugin(overrides?: CallOverrides): Promise<string>;

    guardianPluginManifestHash(overrides?: CallOverrides): Promise<string>;

    multipleOwnerPlugin(overrides?: CallOverrides): Promise<string>;

    multipleOwnerPluginManifestHash(overrides?: CallOverrides): Promise<string>;

    self(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    UNSTAKE_DELAY(overrides?: CallOverrides): Promise<BigNumber>;

    accountImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    addStake(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createAccount(
      owner: PromiseOrValue<string>,
      salt: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    entryPoint(overrides?: CallOverrides): Promise<BigNumber>;

    getAddress(
      owner: PromiseOrValue<string>,
      salt: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSalt(
      owner: PromiseOrValue<string>,
      salt: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    guardianPlugin(overrides?: CallOverrides): Promise<BigNumber>;

    guardianPluginManifestHash(overrides?: CallOverrides): Promise<BigNumber>;

    multipleOwnerPlugin(overrides?: CallOverrides): Promise<BigNumber>;

    multipleOwnerPluginManifestHash(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    self(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    UNSTAKE_DELAY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    accountImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addStake(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createAccount(
      owner: PromiseOrValue<string>,
      salt: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    entryPoint(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAddress(
      owner: PromiseOrValue<string>,
      salt: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSalt(
      owner: PromiseOrValue<string>,
      salt: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    guardianPlugin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    guardianPluginManifestHash(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    multipleOwnerPlugin(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    multipleOwnerPluginManifestHash(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    self(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
